require('core.settings')
require('core.keymaps')
require('core.autocommands')
require('core.plugins')
require('core.colorscheme')

require('core.cursorline')
require('core.autopairs')
require('core.lualine')
require('core.bufferline')
require('core.treesitter')
require('core.lspconfig')
require('core.cmp')
require('core.trouble')
